// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/logpb/log.proto

package logpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Service       string                 `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_proto_logpb_log_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logpb_log_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_proto_logpb_log_proto_rawDescGZIP(), []int{0}
}

func (x *LogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *LogEntry) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type IngestSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      int64                  `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestSummary) Reset() {
	*x = IngestSummary{}
	mi := &file_proto_logpb_log_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestSummary) ProtoMessage() {}

func (x *IngestSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logpb_log_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestSummary.ProtoReflect.Descriptor instead.
func (*IngestSummary) Descriptor() ([]byte, []int) {
	return file_proto_logpb_log_proto_rawDescGZIP(), []int{1}
}

func (x *IngestSummary) GetAccepted() int64 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

var File_proto_logpb_log_proto protoreflect.FileDescriptor

const file_proto_logpb_log_proto_rawDesc = "" +
	"\n" +
	"\x15proto/logpb/log.proto\x12\x03log\"r\n" +
	"\bLogEntry\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\aservice\x18\x03 \x01(\tR\aservice\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\"+\n" +
	"\rIngestSummary\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\x03R\baccepted2?\n" +
	"\n" +
	"LogService\x121\n" +
	"\n" +
	"IngestLogs\x12\r.log.LogEntry\x1a\x12.log.IngestSummary(\x01B*Z(github.com/iliya/crm-service/proto/logpbb\x06proto3"

var (
	file_proto_logpb_log_proto_rawDescOnce sync.Once
	file_proto_logpb_log_proto_rawDescData []byte
)

func file_proto_logpb_log_proto_rawDescGZIP() []byte {
	file_proto_logpb_log_proto_rawDescOnce.Do(func() {
		file_proto_logpb_log_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_logpb_log_proto_rawDesc), len(file_proto_logpb_log_proto_rawDesc)))
	})
	return file_proto_logpb_log_proto_rawDescData
}

var file_proto_logpb_log_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_logpb_log_proto_goTypes = []any{
	(*LogEntry)(nil),      // 0: log.LogEntry
	(*IngestSummary)(nil), // 1: log.IngestSummary
}
var file_proto_logpb_log_proto_depIdxs = []int32{
	0, // 0: log.LogService.IngestLogs:input_type -> log.LogEntry
	1, // 1: log.LogService.IngestLogs:output_type -> log.IngestSummary
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_logpb_log_proto_init() }
func file_proto_logpb_log_proto_init() {
	if File_proto_logpb_log_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_logpb_log_proto_rawDesc), len(file_proto_logpb_log_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_logpb_log_proto_goTypes,
		DependencyIndexes: file_proto_logpb_log_proto_depIdxs,
		MessageInfos:      file_proto_logpb_log_proto_msgTypes,
	}.Build()
	File_proto_logpb_log_proto = out.File
	file_proto_logpb_log_proto_goTypes = nil
	file_proto_logpb_log_proto_depIdxs = nil
}
